module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  breakpoint: 0
  consumers: 0
  contribkanban_api: 0
  contribkanban_boards: 0
  contribkanban_pages: 0
  contribkanban_projects: 0
  contribkanban_users: 0
  dynamic_page_cache: 0
  entity: 0
  field: 0
  file: 0
  filter: 0
  image: 0
  inline_entity_form: 0
  jsonapi: 0
  jsonapi_hypermedia: 0
  jsonapi_resources: 0
  jsonapi_search_api: 0
  jsonapi_user_resources: 0
  lagoon_logs: 0
  layout_discovery: 0
  link: 0
  mailsystem: 0
  node: 0
  options: 0
  page_cache: 0
  path_alias: 0
  rest: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  simple_oauth: 0
  swiftmailer: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_ui: 0
  views: 10
  contribkanban_installer: 1000
theme:
  seven: 0
  contribkanban: 0
profile: contribkanban_installer
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
