transport: native
smtp_host: 127.0.0.1
smtp_port: 25
smtp_encryption: ''
sendmail_path: /usr/sbin/sendmail
sendmail_mode: bs
smtp_credential_provider: swiftmailer
smtp_credentials:
  swiftmailer:
    username: ''
    password: ''
  key:
    username: ''
    password: ''
spool_directory: ''
